#!/usr/bin/env node
// Generates @flocked/abi's sources from the Foundry build output (contracts/out) and the committed deployments.
//
//   node packages/abi/scripts/gen.mjs           write src/{FlockedEscrow,FlockedAnchor,MockUSDC,deployments}.ts
//   node packages/abi/scripts/gen.mjs --check   exit 1 if any generated file differs from what is on disk
//
// Needs only Node built-ins, so CI's contracts job can run it right after `forge build`. The output is already in
// Prettier's style (objects expanded, single quotes, trailing commas). Each file records a hash of the contract
// sources it came from, so `pnpm test` can tell the files are stale without compiling.

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

/** Contracts whose ABIs are generated: Foundry artifact path (under contracts/out) and export name. */
export const CONTRACTS = [
  {
    file: 'FlockedEscrow.ts',
    artifact: 'FlockedEscrow.sol/FlockedEscrow.json',
    name: 'flockedEscrowAbi',
  },
  {
    file: 'FlockedAnchor.ts',
    artifact: 'FlockedAnchor.sol/FlockedAnchor.json',
    name: 'flockedAnchorAbi',
  },
  { file: 'MockUSDC.ts', artifact: 'MockUSDC.sol/MockUSDC.json', name: 'mockUsdcAbi' },
];

/** Chains whose deployment JSON is committed (Base Sepolia, Base). The local chain's file is read at runtime. */
export const COMMITTED_CHAINS = [84532, 8453];

const HASH_PREFIX = '// Inputs: sha256 ';

/** Every file the generated sources depend on, relative to the repo root, sorted. */
export function inputFiles(root = ROOT) {
  const files = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith('.sol')) files.push(path);
    }
  };
  walk(join(root, 'contracts/src'));
  files.push(join(root, 'contracts/test/mocks/MockUSDC.sol'), join(root, 'contracts/soldeer.lock'));
  for (const chainId of COMMITTED_CHAINS) {
    const path = join(root, `contracts/deployments/${chainId}.json`);
    if (existsSync(path)) files.push(path);
  }
  return files.map((f) => relative(root, f).split('\\').join('/')).sort();
}

/** sha256 over the input files' paths and contents (line endings normalized). */
export function inputsHash(root = ROOT) {
  const h = createHash('sha256');
  for (const file of inputFiles(root)) {
    const text = readFileSync(join(root, file), 'utf8').replace(/\r\n/g, '\n');
    h.update(`${file}\n${text.length}\n${text}\n`);
  }
  return h.digest('hex');
}

/** The hash recorded in a generated file's header, or undefined. */
export function recordedHash(source) {
  const line = source.split('\n').find((l) => l.startsWith(HASH_PREFIX));
  return line?.slice(HASH_PREFIX.length).trim();
}

// ---------------------------------------------------------------------------------------------
// Rendering (Prettier-stable TypeScript)
// ---------------------------------------------------------------------------------------------

const pad = (n) => '  '.repeat(n);
const IDENT = /^[A-Za-z_$][\w$]*$/;

function renderKey(key) {
  if (IDENT.test(key) || /^(0|[1-9]\d*)$/.test(key)) return key;
  return renderString(key);
}

function renderString(s) {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function render(value, depth) {
  if (typeof value === 'string') return renderString(value);
  if (typeof value === 'bigint') return `${value}n`;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => `${pad(depth + 1)}${render(v, depth + 1)},\n`).join('');
    return `[\n${items}${pad(depth)}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    const body = entries
      .map(([k, v]) => `${pad(depth + 1)}${renderKey(k)}: ${render(v, depth + 1)},\n`)
      .join('');
    return `{\n${body}${pad(depth)}}`;
  }
  throw new Error(`cannot render ${String(value)}`);
}

function header(hash, from) {
  return [
    `// Generated by packages/abi/scripts/gen.mjs from ${from}. Do not edit: run \`pnpm contracts:build\`.`,
    `${HASH_PREFIX}${hash}`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------------------------

function readAbi(root, artifact) {
  const path = join(root, 'contracts/out', artifact);
  if (!existsSync(path)) {
    throw new Error(
      `${relative(root, path)} not found: run \`forge build --root contracts\` first`,
    );
  }
  const { abi } = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(abi)) throw new Error(`${artifact} has no abi`);
  return abi;
}

const ADDRESS = /^0x[0-9a-fA-F]{40}$/;

function readDeployment(root, chainId) {
  const path = join(root, `contracts/deployments/${chainId}.json`);
  const d = JSON.parse(readFileSync(path, 'utf8'));
  for (const k of ['escrow', 'anchor', 'usdc']) {
    if (typeof d[k] !== 'string' || !ADDRESS.test(d[k]))
      throw new Error(`${chainId}.json: bad ${k}`);
  }
  if (!Number.isSafeInteger(d.deployBlock) || d.deployBlock < 0) {
    throw new Error(`${chainId}.json: bad deployBlock`);
  }
  return { escrow: d.escrow, anchor: d.anchor, usdc: d.usdc, deployBlock: BigInt(d.deployBlock) };
}

/** Renders every generated file. Returns `{ hash, files }` with paths relative to packages/abi. */
export function generate(root = ROOT) {
  const hash = inputsHash(root);
  const files = {};
  for (const c of CONTRACTS) {
    const abi = readAbi(root, c.artifact);
    files[`src/${c.file}`] =
      `${header(hash, `contracts/out/${c.artifact}`)}\nexport const ${c.name} = ${render(abi, 0)} as const;\n`;
  }

  const deployments = {};
  for (const chainId of COMMITTED_CHAINS) {
    if (existsSync(join(root, `contracts/deployments/${chainId}.json`))) {
      deployments[chainId] = readDeployment(root, chainId);
    }
  }
  files['src/deployments.ts'] = [
    header(hash, 'contracts/deployments/{84532,8453}.json'),
    "import type { Deployment } from './addresses';",
    '',
    '/** Deployments committed to the repo, by chain ID. The local chain (31337) is never committed. */',
    `export const committedDeployments: Readonly<Partial<Record<number, Deployment>>> = ${render(deployments, 0)};`,
    '',
  ].join('\n');
  return { hash, files };
}

function main() {
  const check = process.argv.includes('--check');
  const pkg = resolve(ROOT, 'packages/abi');
  const { files } = generate();
  const stale = [];
  for (const [file, content] of Object.entries(files)) {
    const path = join(pkg, file);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
    if (current === content) continue;
    stale.push(file);
    if (!check) writeFileSync(path, content);
  }
  if (check && stale.length > 0) {
    console.error(
      `@flocked/abi is stale: ${stale.join(', ')}. Run \`pnpm contracts:build\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(check ? '@flocked/abi is current' : `@flocked/abi: ${stale.length} file(s) written`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main();
