// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {MerkleProof} from "@openzeppelin-contracts/utils/cryptography/MerkleProof.sol";
import {IFlockedEscrow} from "../src/interfaces/IFlockedEscrow.sol";
import {EscrowBase} from "./utils/EscrowBase.sol";
import {TestMerkle} from "./utils/TestMerkle.sol";

/// @notice Checks the stakes-payout-merkle vectors the settle package generates (P1.1, CON-13): every recorded proof
///         verifies against its root with OpenZeppelin `MerkleProof`, and one tree pays out through a real `claim`.
/// @dev The file is ~185 KB, so it is read into memory per test and passed around; keeping it in storage makes every
///      cheatcode call re-read it and runs out of gas.
contract MerkleVectorsTest is EscrowBase {
    /// @dev Relative to the Foundry project root. Generated by `pnpm --filter @flocked/settle vectors`.
    string internal constant PATH = "../packages/settle/vectors/stakes-payout-merkle.json";

    /// @dev The vector settled on chain: 2 Win, 22 Rebate and 1 VoidRefund leaves, 5 USDC stake, round id 10.
    string internal constant CLAIM_VECTOR = "small-settled";

    function _read() internal view returns (string memory) {
        return vm.readFile(string.concat(vm.projectRoot(), "/", PATH));
    }

    function _u(string memory j, string memory key) internal pure returns (uint256) {
        return vm.parseUint(vm.parseJsonString(j, key));
    }

    function _len(string memory j, string memory arrayKey) internal view returns (uint256 n) {
        while (vm.keyExistsJson(j, string.concat(arrayKey, "[", vm.toString(n), "]"))) {
            n++;
        }
    }

    function _vectorBase(string memory j, string memory id) internal view returns (string memory) {
        uint256 n = _len(j, ".vectors");
        for (uint256 i; i < n; i++) {
            string memory b = string.concat(".vectors[", vm.toString(i), "]");
            if (keccak256(bytes(vm.parseJsonString(j, string.concat(b, ".id")))) == keccak256(bytes(id))) return b;
        }
        revert(string.concat("vector not found: ", id));
    }

    function _proofAt(string memory j, string memory p)
        internal
        pure
        returns (address account, uint8 kind, bytes32[] memory proof)
    {
        account = vm.parseJsonAddress(j, string.concat(p, ".account"));
        kind = uint8(_u(j, string.concat(p, ".kind")));
        proof = vm.parseJsonBytes32Array(j, string.concat(p, ".proof"));
    }

    function test_merkleVectors_header() public view {
        string memory j = _read();
        assertEq(vm.parseJsonString(j, ".kind"), "stakes-payout-merkle");
        assertGe(_len(j, ".vectors"), 4);
    }

    function test_merkleVectors_everyProofVerifies() public view {
        string memory j = _read();
        uint256 n = _len(j, ".vectors");
        uint256 checked;
        bool sawLarge;
        for (uint256 i; i < n; i++) {
            string memory b = string.concat(".vectors[", vm.toString(i), "]");
            string memory id = vm.parseJsonString(j, string.concat(b, ".id"));
            uint256 roundId = _u(j, string.concat(b, ".chainRoundId"));
            bytes32 root = vm.parseJsonBytes32(j, string.concat(b, ".root"));
            if (vm.keyExistsJson(j, string.concat(b, ".leaves[999]"))) sawLarge = true;

            uint256 m = _len(j, string.concat(b, ".proofs"));
            assertGt(m, 0, string.concat(id, ": no proofs"));
            for (uint256 k; k < m; k++) {
                (address account, uint8 kind, bytes32[] memory proof) =
                    _proofAt(j, string.concat(b, ".proofs[", vm.toString(k), "]"));
                bytes32 leaf = TestMerkle.leaf(roundId, account, kind);
                assertTrue(MerkleProof.verify(proof, root, leaf), string.concat(id, ": proof ", vm.toString(k)));
                // The same proof must not verify another round id or kind.
                assertFalse(MerkleProof.verify(proof, root, TestMerkle.leaf(roundId + 1, account, kind)));
                assertFalse(MerkleProof.verify(proof, root, TestMerkle.leaf(roundId, account, (kind + 1) % 3)));
                checked++;
            }
        }
        assertTrue(sawLarge, "a tree with >= 1000 leaves");
        assertGe(checked, 60);
    }

    function test_merkleVectors_claimOnSettledRound() public {
        string memory j = _read();
        string memory b = _vectorBase(j, CLAIM_VECTOR);
        uint256 chainRoundId = _u(j, string.concat(b, ".chainRoundId"));
        bytes32 root = vm.parseJsonBytes32(j, string.concat(b, ".root"));

        // The tally the tree attests to, from its leaf kinds.
        uint256 leafCount = _len(j, string.concat(b, ".leaves"));
        uint32[3] memory perKind;
        for (uint256 i; i < leafCount; i++) {
            perKind[_u(j, string.concat(b, ".leaves[", vm.toString(i), "].kind"))]++;
        }
        assertLt(perKind[0], perKind[1], "winners are the minority option 0");

        // Burn round ids so the settled round's id equals the vector's chainRoundId.
        while (escrow.roundCount() + 1 < chainRoundId) {
            _createDefault();
        }
        uint256 id = _createDefault();
        assertEq(id, chainRoundId);

        // The vector's accounts are the entrants (claim requires an entry).
        _warpOpen(id);
        for (uint256 i; i < leafCount; i++) {
            _enter(id, vm.parseJsonAddress(j, string.concat(b, ".leaves[", vm.toString(i), "].account")));
        }
        _warpBeacon(id);
        vm.prank(operator);
        escrow.propose(id, perKind[0], perKind[1], perKind[2], root, keccak256("bundle"));
        _warpClaimsOpen(id);

        IFlockedEscrow.Round memory rd = escrow.getRound(id);
        assertEq(uint8(rd.status), uint8(IFlockedEscrow.Status.SettleProposed));
        assertGt(rd.rebatePayout, 0, "rebate leaves need r > 0");
        uint256[3] memory amountOf = [uint256(rd.winPayout), uint256(rd.rebatePayout), uint256(rd.cfg.stake)];

        uint256 m = _len(j, string.concat(b, ".proofs"));
        assertEq(m, leafCount, "every leaf has a recorded proof");
        for (uint256 k; k < m; k++) {
            (address account, uint8 kind, bytes32[] memory proof) =
                _proofAt(j, string.concat(b, ".proofs[", vm.toString(k), "]"));
            uint256 before = usdc.balanceOf(account);
            vm.prank(account);
            escrow.claim(id, IFlockedEscrow.Kind(kind), proof);
            assertEq(usdc.balanceOf(account) - before, amountOf[kind]);
            assertTrue(escrow.hasClaimed(id, account));
        }

        assertEq(uint8(escrow.getRound(id).status), uint8(IFlockedEscrow.Status.Settled));
        // Every payout is claimed: only the treasury and creator credits remain owed, and the escrow holds exactly that.
        uint256 credits = escrow.withdrawable(treasury) + escrow.withdrawable(creator);
        assertEq(escrow.totalObligations(), credits);
        assertEq(usdc.balanceOf(address(escrow)), credits);
    }
}
