// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";

import {FlockedAnchor} from "../src/FlockedAnchor.sol";
import {FlockedEscrow} from "../src/FlockedEscrow.sol";
import {IFlockedAnchor} from "../src/interfaces/IFlockedAnchor.sol";
import {IFlockedEscrow} from "../src/interfaces/IFlockedEscrow.sol";

/// @notice Checks the EIP-712 digests `@flocked/shared` computes (ticket for FlockedEscrow, receipt for FlockedAnchor)
///         and its round keys against the contracts, deployed at the fixture's addresses on the fixture's chain id.
/// @dev The fixture is small but is still read into memory per test (see `MerkleVectors.t.sol`).
contract SharedEip712Test is Test {
    /// @dev Relative to the Foundry project root. Generated by `packages/shared/test/eip712-fixture.ts`.
    string internal constant PATH = "../packages/shared/test/fixtures/eip712.json";

    bytes32 internal constant EIP712_DOMAIN_TYPEHASH =
        keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)");

    uint64 internal constant GENESIS = 1692803367; // drand quicknet
    uint64 internal constant PERIOD = 3;

    FlockedEscrow internal escrow;
    FlockedAnchor internal anchor;

    function _read() internal view returns (string memory) {
        return vm.readFile(string.concat(vm.projectRoot(), "/", PATH));
    }

    function _u(string memory j, string memory key) internal pure returns (uint256) {
        return vm.parseUint(vm.parseJsonString(j, key));
    }

    function setUp() public {
        string memory j = _read();
        vm.chainId(_u(j, ".chainId"));

        address escrowAt = vm.parseJsonAddress(j, ".escrow");
        address anchorAt = vm.parseJsonAddress(j, ".anchor");
        deployCodeTo(
            "FlockedEscrow.sol:FlockedEscrow",
            abi.encode(
                makeAddr("usdc"),
                makeAddr("admin"),
                makeAddr("guardian"),
                makeAddr("operator"),
                makeAddr("pauser"),
                makeAddr("ticketSigner"),
                makeAddr("treasury"),
                GENESIS,
                PERIOD
            ),
            escrowAt
        );
        deployCodeTo(
            "FlockedAnchor.sol:FlockedAnchor",
            abi.encode(makeAddr("admin"), makeAddr("anchorer"), makeAddr("receiptSigner"), GENESIS, PERIOD),
            anchorAt
        );
        escrow = FlockedEscrow(escrowAt);
        anchor = FlockedAnchor(anchorAt);
    }

    function _domain(address verifyingContract) internal view returns (bytes32) {
        return keccak256(
            abi.encode(EIP712_DOMAIN_TYPEHASH, keccak256("Flocked"), keccak256("1"), block.chainid, verifyingContract)
        );
    }

    /// @dev Crockford base32 ULID (26 chars) to its 16 bytes.
    function _ulidToBytes16(string memory ulid) internal pure returns (bytes16) {
        bytes memory s = bytes(ulid);
        bytes memory alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
        require(s.length == 26, "ULID length");
        uint256 v;
        for (uint256 i; i < 26; i++) {
            uint256 d = 32;
            for (uint256 k; k < 32; k++) {
                if (alphabet[k] == s[i]) d = k;
            }
            require(d < 32, "ULID character");
            v = (v << 5) | d;
        }
        require(v >> 128 == 0, "ULID overflow");
        return bytes16(uint128(v));
    }

    function test_sharedEip712_deployedAtFixture() public view {
        string memory j = _read();
        assertEq(block.chainid, 84532, "Base Sepolia");
        assertEq(address(escrow), vm.parseJsonAddress(j, ".escrow"));
        assertEq(address(anchor), vm.parseJsonAddress(j, ".anchor"));
        assertGt(address(escrow).code.length, 0, "escrow code");
        assertGt(address(anchor).code.length, 0, "anchor code");
        assertEq(escrow.domainSeparator(), _domain(address(escrow)), "escrow domain separator");
        assertEq(anchor.domainSeparator(), _domain(address(anchor)), "anchor domain separator");
    }

    function test_sharedEip712_ticketDigest() public view {
        string memory j = _read();
        IFlockedEscrow.EntryTicket memory t = IFlockedEscrow.EntryTicket({
            roundId: _u(j, ".ticket.roundId"),
            wallet: vm.parseJsonAddress(j, ".ticket.wallet"),
            personTag: vm.parseJsonBytes32(j, ".ticket.personTag"),
            expiry: uint64(_u(j, ".ticket.expiry"))
        });
        assertEq(escrow.ticketDigest(t), vm.parseJsonBytes32(j, ".ticketDigest"), "ticketDigest");
    }

    function test_sharedEip712_receiptDigest() public view {
        string memory j = _read();
        bytes memory roundId = vm.parseJsonBytes(j, ".receipt.roundId");
        assertEq(roundId.length, 16, "receipt roundId is bytes16");
        IFlockedAnchor.Receipt memory r = IFlockedAnchor.Receipt({
            roundId: bytes16(roundId),
            mode: uint8(_u(j, ".receipt.mode")),
            userIdHash: vm.parseJsonBytes32(j, ".receipt.userIdHash"),
            stake: uint64(_u(j, ".receipt.stake")),
            commitment: vm.parseJsonBytes32(j, ".receipt.commitment"),
            seq: uint32(_u(j, ".receipt.seq")),
            closesAt: uint64(_u(j, ".receipt.closesAt")),
            beaconRound: uint64(_u(j, ".receipt.beaconRound"))
        });
        assertEq(anchor.receiptDigest(r), vm.parseJsonBytes32(j, ".receiptDigest"), "receiptDigest");
    }

    function test_sharedEip712_roundKeys() public view {
        string memory j = _read();
        bytes16 roundId = bytes16(vm.parseJsonBytes(j, ".receipt.roundId"));
        assertEq(roundId, _ulidToBytes16(vm.parseJsonString(j, ".roundUlid")), "roundUlid decodes to receipt.roundId");
        assertEq(anchor.roundKey(roundId, 0), vm.parseJsonBytes32(j, ".roundKeys.free"), "roundKeys.free");
        assertEq(anchor.roundKey(roundId, 1), vm.parseJsonBytes32(j, ".roundKeys.stakes"), "roundKeys.stakes");
    }
}
