// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {console} from "forge-std/console.sol";

import {FlockedEscrow} from "../src/FlockedEscrow.sol";
import {IFlockedEscrow} from "../src/interfaces/IFlockedEscrow.sol";
import {EscrowBase} from "./utils/EscrowBase.sol";

/// @notice TL-4: replays the tlock target-round vectors (P2.1) through `createRound`. Each case runs against an escrow
///         deployed with the case's drand (genesis, period) and an otherwise valid config; the contract must revert
///         with exactly the case's `contractError`, and accept every other case (including those only the client
///         refuses, since the client is stricter than the contract).
/// @dev The file is read into memory per test and passed around (see `MerkleVectors.t.sol`).
contract TargetRoundTest is EscrowBase {
    /// @dev Relative to the Foundry project root. Generated by the tlock package (W2-A).
    string internal constant PATH = "../packages/tlock/vectors/target-round.json";

    /// @dev The two synthetic chains the vectors use besides quicknet: (1700000000, 1) and (1700000000, 30).
    uint64 internal constant SYNTHETIC_GENESIS = 1_700_000_000;

    struct Case {
        string id;
        uint64 closesAt;
        uint64 beaconRound;
        uint64 genesis;
        uint64 period;
        uint256 beaconDelay;
        bool expectedOk;
        string reason;
        string contractError;
    }

    /// @dev One escrow per distinct (genesis, period), deployed on first use.
    struct Escrows {
        uint64[] genesis;
        uint64[] period;
        FlockedEscrow[] escrow;
        uint256 count;
    }

    struct Tally {
        uint256 ok;
        uint256 invalidBeaconRound;
        uint256 beaconOutOfRange;
        uint256 clientOnly;
        bool quicknet;
        bool period1;
        bool period30;
    }

    function _read() internal view returns (string memory) {
        return vm.readFile(string.concat(vm.projectRoot(), "/", PATH));
    }

    function _u(string memory j, string memory key) internal pure returns (uint256) {
        return vm.parseUint(vm.parseJsonString(j, key));
    }

    function _len(string memory j) internal view returns (uint256 n) {
        while (vm.keyExistsJson(j, string.concat(".cases[", vm.toString(n), "]"))) {
            n++;
        }
    }

    function _case(string memory j, uint256 i) internal pure returns (Case memory c) {
        string memory b = string.concat(".cases[", vm.toString(i), "]");
        c.id = vm.parseJsonString(j, string.concat(b, ".id"));
        c.closesAt = uint64(_u(j, string.concat(b, ".closesAt")));
        c.beaconRound = uint64(_u(j, string.concat(b, ".beaconRound")));
        c.genesis = uint64(_u(j, string.concat(b, ".genesis")));
        c.period = uint64(_u(j, string.concat(b, ".period")));
        c.beaconDelay = _u(j, string.concat(b, ".beaconDelay"));
        c.expectedOk = vm.parseJsonBool(j, string.concat(b, ".expectedOk"));
        c.reason = vm.parseJsonString(j, string.concat(b, ".reason"));
        c.contractError = vm.parseJsonString(j, string.concat(b, ".contractError"));
    }

    function _escrowFor(Escrows memory es, uint64 genesis, uint64 period) internal returns (FlockedEscrow e) {
        for (uint256 k; k < es.count; k++) {
            if (es.genesis[k] == genesis && es.period[k] == period) return es.escrow[k];
        }
        e = new FlockedEscrow(usdc, admin, guardian, operator, pauser, signer, treasury, genesis, period);
        es.genesis[es.count] = genesis;
        es.period[es.count] = period;
        es.escrow[es.count] = e;
        es.count++;
    }

    /// @dev A valid config (see `EscrowBase._cfg`) except for the case's `closesAt` and `beaconRound`.
    function _cfgFor(Case memory c) internal view returns (IFlockedEscrow.RoundConfig memory cfg) {
        cfg = _cfg();
        cfg.closesAt = c.closesAt;
        cfg.opensAt = c.closesAt - 1 hours;
        cfg.beaconRound = c.beaconRound;
    }

    function _revertData(string memory id, string memory name) internal pure returns (bytes memory) {
        bytes32 h = keccak256(bytes(name));
        if (h == keccak256("InvalidBeaconRound")) {
            return abi.encodeWithSelector(IFlockedEscrow.InvalidBeaconRound.selector);
        }
        if (h == keccak256("BeaconOutOfRange")) {
            return abi.encodeWithSelector(IFlockedEscrow.BeaconOutOfRange.selector);
        }
        revert(string.concat(id, ": unknown contractError ", name));
    }

    /// @dev Runs one case through `createRound` on `e` and checks the outcome against `contractError`.
    function _replay(FlockedEscrow e, Case memory c) internal returns (bool accepted) {
        IFlockedEscrow.RoundConfig memory cfg = _cfgFor(c);
        vm.warp(cfg.opensAt - 1 minutes);
        vm.prank(operator);
        try e.createRound(cfg) returns (uint256 roundId) {
            assertEq(c.contractError, "", string.concat(c.id, ": contract accepted, vectors expect a revert"));
            IFlockedEscrow.Round memory rd = e.getRound(roundId);
            assertEq(rd.cfg.closesAt, c.closesAt, string.concat(c.id, ": stored closesAt"));
            assertEq(rd.cfg.beaconRound, c.beaconRound, string.concat(c.id, ": stored beaconRound"));
            accepted = true;
        } catch (bytes memory err) {
            if (bytes(c.contractError).length == 0) {
                fail(string.concat(c.id, ": contract reverted with ", vm.toString(err), ", vectors expect success"));
            }
            assertEq(err, _revertData(c.id, c.contractError), string.concat(c.id, ": revert data"));
        }
    }

    /// @dev A client-accepted target is the first drand round at or after `closesAt + beaconDelay`, by the contract's
    ///      own `beaconTime`.
    function _checkFirstRound(FlockedEscrow e, Case memory c) internal view {
        uint256 target = uint256(c.closesAt) + c.beaconDelay;
        assertGe(e.beaconTime(c.beaconRound), target, string.concat(c.id, ": beacon before closesAt + beaconDelay"));
        if (c.beaconRound > 1) {
            assertLt(e.beaconTime(c.beaconRound - 1), target, string.concat(c.id, ": not the first such round"));
        }
    }

    function _count(Tally memory t, Case memory c) internal pure {
        if (c.genesis == GENESIS && c.period == PERIOD) t.quicknet = true;
        if (c.genesis == SYNTHETIC_GENESIS && c.period == 1) t.period1 = true;
        if (c.genesis == SYNTHETIC_GENESIS && c.period == 30) t.period30 = true;

        bytes32 h = keccak256(bytes(c.contractError));
        if (h == keccak256("InvalidBeaconRound")) t.invalidBeaconRound++;
        else if (h == keccak256("BeaconOutOfRange")) t.beaconOutOfRange++;
        else if (c.expectedOk) t.ok++;
        else t.clientOnly++;
    }

    function test_targetRound_vectorsMatchCreateRound() public {
        string memory j = _read();
        uint256 n = _len(j);
        assertGt(n, 0, "no cases");

        Escrows memory es = Escrows(new uint64[](n), new uint64[](n), new FlockedEscrow[](n), 0);
        Tally memory t;
        for (uint256 i; i < n; i++) {
            Case memory c = _case(j, i);
            // The client never accepts a target the contract would reject.
            if (c.expectedOk) assertEq(c.contractError, "", string.concat(c.id, ": client accepts a contract error"));

            FlockedEscrow e = _escrowFor(es, c.genesis, c.period);
            bool accepted = _replay(e, c);
            if (c.expectedOk) _checkFirstRound(e, c);
            if (!c.expectedOk && accepted) {
                console.log("client-only rejection:", c.id, c.reason);
            }
            _count(t, c);
        }

        assertTrue(t.quicknet, "a quicknet case");
        assertTrue(t.period1, "a (1700000000, 1) case");
        assertTrue(t.period30, "a (1700000000, 30) case");
        assertGt(t.ok, 0, "an accepted case");
        assertGt(t.invalidBeaconRound, 0, "an InvalidBeaconRound case");
        assertGt(t.beaconOutOfRange, 0, "a BeaconOutOfRange case");
        assertGt(t.clientOnly, 0, "a client-only rejection");
        assertEq(t.ok + t.invalidBeaconRound + t.beaconOutOfRange + t.clientOnly, n);

        console.log("cases", n, "chains", es.count);
        console.log("ok", t.ok, "client-only rejections", t.clientOnly);
        console.log("InvalidBeaconRound", t.invalidBeaconRound, "BeaconOutOfRange", t.beaconOutOfRange);
    }
}
