// Generated by packages/abi/scripts/gen.mjs from contracts/deployments/{84532,8453}.json. Do not edit: run `pnpm contracts:build`.
// Inputs: sha256 2f2d9c866cd0526516057d9c67bbb0c4cdc1bab6cdd69bd3356954b7fde011c4

import type { Deployment } from './addresses';

/** Deployments committed to the repo, by chain ID. The local chain (31337) is never committed. */
export const committedDeployments: Readonly<Partial<Record<number, Deployment>>> = {};
