// Worker bindings and vars (wrangler.jsonc). Hand-written rather than generated by `wrangler types`
// so it stays reviewable; test/worker.test.ts touches every binding in the Workers runtime and checks
// wrangler.jsonc against the code, so drift fails a test.
import type { CardsMessage, DecryptMessage, NotifyMessage, SettleMessage } from '@flocked/shared';
import type {
  AnchorDO,
  AuthDO,
  IndexerDO,
  RateLimitDO,
  RoundDO,
  RoundViewerDO,
  SettlementDO,
} from './do/index.js';

/** `ENVIRONMENT` var (plan 4.4). */
export type Environment = 'local' | 'staging' | 'production';

export interface Env {
  // Storage (spec "Architecture": Storage).
  DB: D1Database;
  BUCKET: R2Bucket;
  KV: KVNamespace;

  // Durable Objects (spec "Architecture"). One RoundDO per round, RoundViewerDO shards per round,
  // AnchorDO / IndexerDO singletons, one SettlementDO per (round, mode).
  ROUND: DurableObjectNamespace<RoundDO>;
  ROUND_VIEWER: DurableObjectNamespace<RoundViewerDO>;
  ANCHOR: DurableObjectNamespace<AnchorDO>;
  SETTLEMENT: DurableObjectNamespace<SettlementDO>;
  AUTH: DurableObjectNamespace<AuthDO>;
  RATE_LIMIT: DurableObjectNamespace<RateLimitDO>;
  INDEXER: DurableObjectNamespace<IndexerDO>;

  // Queue producers; message shapes from @flocked/shared (queues.ts).
  QUEUE_SETTLE: Queue<SettleMessage>;
  QUEUE_DECRYPT_DAILY: Queue<DecryptMessage>;
  QUEUE_DECRYPT_ROOMS: Queue<DecryptMessage>;
  QUEUE_CARDS: Queue<CardsMessage>;
  QUEUE_NOTIFY: Queue<NotifyMessage>;

  // Platform services.
  ANALYTICS: AnalyticsEngineDataset;
  VECTORIZE: Vectorize;
  AI: Ai;
  EMAIL: SendEmail;
  /** Static assets for apps/web. */
  ASSETS: Fetcher;

  // Vars (all strings, as wrangler passes them).
  ENVIRONMENT: Environment;
  /** 31337 local (anvil), 84532 staging (Base Sepolia), 8453 production (Base). */
  CHAIN_ID: string;
  DRAND_CHAIN_HASH: string;
  DRAND_PUBLIC_KEY: string;
  DRAND_GENESIS: string;
  DRAND_PERIOD: string;

  /** Epoch ms; honoured only when ENVIRONMENT is 'local' (src/lib/clock.ts). Tests and e2e only. */
  FLOCKED_TEST_CLOCK?: string;

  // Secrets (wrangler.jsonc header lists them). Optional until the owning session needs them.
  TURNSTILE_SECRET_KEY?: string;
  RECEIPT_SIGNER_KEY?: string;
  PERSON_ID_KEY?: string;
  PERSON_TAG_KEY?: string;
  COINBASE_CLIENT_ID?: string;
  COINBASE_CLIENT_SECRET?: string;
  ANCHOR_KEY?: string;
  OPERATOR_KEY?: string;
  BASE_RPC_URL?: string;
  BASE_RPC_URL_FALLBACK?: string;
  ANTHROPIC_API_KEY?: string;
  VAPID_PRIVATE_KEY?: string;
  PAYMASTER_URL?: string;
  BUNDLER_URL?: string;
}
